{{- if .Values.expose }}
{{- if .Values.expose.config }}
{{- if .Values.expose.config.tlsacme }}
{{- if eq .Values.expose.config.tlsacme "true" }}
apiVersion: v1
data:
  tls.crt: Zm9vIC1uCg==
  tls.key: Zm9vIC1uCg==
kind: Secret
metadata:
  annotations:
{{- if .Values.expose.production }}
    replicator.v1.mittwald.de/replicate-from: jx/tls-{{ .Values.expose.config.domain | replace "." "-" }}-p
{{- else }}
    replicator.v1.mittwald.de/replicate-from: jx/tls-{{ .Values.expose.config.domain | replace "." "-" }}-s
{{- end }}
{{- if .Values.expose.production }}
  name: "tls-{{ .Values.expose.config.domain | replace "." "-" }}-p"
{{- else }}
  name: "tls-{{ .Values.expose.config.domain | replace "." "-" }}-s"
{{- end }}
type: kubernetes.io/tls
{{- end }}
{{- end }}
{{- end }}
{{- end }}
