apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-marketplace
  namespace: watchlist
spec:
  selector:
    matchLabels:
      app: movies-marketplace
  template:
    metadata: 
      labels: 
        app: movies-marketplace
    spec:
      containers:
      - name: movies-marketplace
        image: 305929695733.dkr.ecr.eu-west-3.amazonaws.com/mlabouardy/movies-marketplace:develop
        ports:
        - containerPort: 80