apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-parser
  namespace: watchlist
spec:
  selector:
    matchLabels:
      app: movies-parser
  template:
    metadata: 
      labels: 
        app: movies-parser
    spec:
      containers:
      - name: movies-parser
        image: 305929695733.dkr.ecr.eu-west-3.amazonaws.com/mlabouardy/movies-parser:develop
        env:
        - name: AWS_REGION
          value: eu-west-3
        - name: SQS_URL
          value: https://sqs.eu-west-3.amazonaws.com/305929695733/movies_to_parse_sandbox
        - name: MONGO_DATABASE
          valueFrom:
            secretKeyRef:
              name: mongodb-access
              key: database
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-access
              key: uri